### ISSUE TITLE
Playground v2 - API refactor

### ISSUE THREAD

**Issue by sideninja** [onflow/flow-playground-api#82] opened 2022-09-29 16:31 UTC
We will need to change the API endpoints to accommodate the changes from the refactoring of accounts and contracts. Furthermore at this point, we should optimize those endpoints as currently there are always requests done in pairs by the client (deploy contract, get project to update). Those requests should have required data in response in the first place to optimize round trips.

**Comment by DylanTinianov** [comment] 2022-10-04 15:04
Duplicate of https://github.com/onflow/flow-playground-api/issues/73

**Closed by DylanTinianov** 2022-10-04 15:04 UTC
Labels: v2, mvp
